apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: my-pipeline
spec:
  sideInputs:
    - name: myticker
      container:
        image: "quay.io/numaio/numaflow-go/sideinput:v3"
        imagePullPolicy: Always
      trigger:
        schedule: "*/2 * * * *"
        # interval: 180s
        # timezone: America/Los_Angeles
  vertices:
    - name: in
      source:
        # A self data generating source
        generator:
          rpu: 1
          duration: 1s
    - name: si-log
      udf:
        container:
          image: "quay.io/numaio/numaflow-go/udf-sideinput:v3"
          imagePullPolicy: Always
          env:
            - name: SIDEINPUT_PATH
              value: "/var/numaflow/side-inputs"
            - name: SIDEINPUT_NAME
              value: "myticker"
      containerTemplate:
        env:
          - name: NUMAFLOW_DEBUG
            value: "true" # DO NOT forget the double quotes!!!
      sideInputs:
        - myticker
    - name: out
      sink:
        # A simple log printing sink
        log: {}
  edges:
    - from: in
      to: si-log
    - from: si-log
      to: out