apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: my-pipeline
spec:
  sideInputs:
    - name: devportal
      container:
        image: "quay.io/numaio/numaflow-go/sideinput:v3"
      trigger:
        schedule: "*/3 * * * *"
        # interval: 180s
        # timezone: America/Los_Angeles
  vertices:
    - name: in
      source:
        # A self data generating source
        generator:
          rpu: 200
          duration: 1s
    - name: cat
      udf:
        builtin:
          name: cat # A built-in UDF which simply cats the message
      containerTemplate:
        env:
          - name: NUMAFLOW_DEBUG
            value: "true" # DO NOT forget the double quotes!!!
      sideInputs:
        - devportal
    - name: out
      sink:
        # A simple log printing sink
        log: {}
  edges:
    - from: in
      to: cat
    - from: cat
      to: out