apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  watermark:
    disabled: false # Optional, defaults to false.
  limits:
    readBatchSize: 2
  vertices:
    - name: in
      source:
        http: { }
#    - name: in
#      source:
#        # A self data generating source
#        generator:
#          rpu: 10
#          duration: 1s
    - name: flatmap
      scale:
        min: 1
      metadata:
        annotations:
          numaflow.numaproj.io/flat-map: "true"
      limits:
        readBatchSize: 10
      udf:
        container:
          image: "quay.io/kohlisid/numaflow-go/map-flatmap:ged3"
          imagePullPolicy: Always
          env:
            - name: PYTHONDEBUG
              value: "true"
            - name : INVOKE
              value: "func_handler"
      containerTemplate:
        env:
          - name: NUMAFLOW_DEBUG
            value: "true" # DO NOT forget the double quotes!!!
    - name: out
      scale:
        min: 1
      sink:
        # A simple log printing sink
        log: {}
  edges:
    - from: in
      to: flatmap
    - from: flatmap
      to: out
